# https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    groups:
      mediabunny:
        patterns:
          - "mediabunny"
          - "@mediabunny/*"
      typescript-eslint:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
